export { default as LoginModule } from './Login';
export { default as AccountModule } from './Account';
export { default as TribeModule } from './Tribe';
export { default as TribeDetailModule } from './Tribe/detail';
export { default as NewTribeModule } from './Tribe/new';
export { default as LocationModule } from './Location';
export { default as NewLocationModule } from './Location/new';
export { default as LocationDetailModule } from './Location/detail';
export { default as ManageModule } from './Manage';